### PR TITLE
Remove references to parity-ethereum

### PR DESCRIPTION
**Pull request by s3krit**
This is a general PR to remove/replace instances of Parity-Ethereum from the project. For starters, I have just changed the links in the CHANGELOGs and README.md to reflect the new home for this project. Moving forwards, we'd also want to change references to things like blogs, wiki pages, etc. but perhaps that can happen as the Open Ethereum community makes decisions on what we want to implement.

### CODE REVIEW

**Comment by ordian** [comment]
other references to be renamed
```
ethcore/types/src/errors/mod.rs
17://! General error types for use in parity-ethereum.
ethcore/trace/src/types/trace.rs
150:/// the older encodings used in parity-ethereum versions < 2.7 and 2.7.0.
util/network-devp2p/src/discovery.rs
587:							trace!(target: "discovery", "Got Pong from an old parity-ethereum version.");
scripts/docker/README.md
10:cd parity-ethereum
ethash/src/compute.rs
267:			compile_error!("parity-ethereum currently only supports little-endian targets");
```
Do we want to rename the binary name as well?

**Comment by vorot93** [comment]
@ordian we do

**Comment by ordian** [comment]
> Do we want to rename the binary name as well?

I meant in this PR or in another? This renaming might break a few things like our current CI for example.

**Comment by vorot93** [comment]
@ordian I suppose we could do it after GH actions is merged then.

**Pull request merged**
